extends:
  - stylelint-config-standard
  - stylelint-config-prettier

rules:
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - global
  property-no-unknown:
    - true
    - ignoreProperties:
        - composes

